name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
jobs:
  security-checks:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
    - name: Build the test image
      run: docker build . --file Dockerfile --tag localbuild/testimage:latest
    - name: Grype scan the test image
      uses: anchore/scan-action@v3
      id: scan
      with:
        image: "localbuild/testimage:latest"
        fail-build: false
        severity-cutoff: critical
    - name: Upload vulnerability report
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}

  build-deployment:
    needs: security-checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ocpdude/safe-settings:$(date +%s) ocpdude/safe-settings:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.MYTOKEN }}
